#!/bin/bash
# Author: Dickson Esakenong
# Date: 11/03/2022
# Description: This is an if then conditions script
# Date Modified: 11/03/22


count=1
if [ $count -eq 100 ]
then
 echo count is 100
else
 echo count is not 100
fi
